#!/bin/sh

default_connection=corp-HN

## Bring up default connection or the Link Connection your specified in the shell script argument.
if [[ $1 == '' ]]; then
  nmcli c up $default_connection passwd-file ./passwd-file
else
  nmcli c up $1 passwd-file ./passwd-file
fi
# case $1 in
#   '' )
#     nmcli c up $default_connection passwd-file ./passwd-file;;
#   * )
#     nmcli c up $1 passwd-file ./passwd-file
# esac

## Return result.
[ $? == 0 ] \
&& echo -e "\033[1;34;40m[ \033[5;32;40m^_^ Greetings! May the Force be with you! \033[1;34;40m]\033[0m \n" \
|| echo -e "\033[1;34;40m[ \033[5;31;40mv_v Sadlly! Something is WRONG? \033[1;34;40m]\033[0m \n"

## Show the Link Connections state.
echo -e "\033[0;33mHere are all the Link Connections you have own in NetworkManager: \033[0m"
nmcli c s
