#!/bin/bash
# filename: venv_py39
# description: create and|or activate virtual environment for python3.9
# Usage: . venv_py39

PYTHON_BIN=/usr/bin/python3.9
VENV=.venv_py39
VENV_DIR=$(pwd)/$VENV  # 这个变量设置将用来在当前目录下创建 $VENV 目录，作为虚拟环境的根目录。

venv_create() {
    $PYTHON_BIN -m venv $VENV_DIR
}

venv_activate() {
    source $VENV_DIR/bin/activate
    echo "Virtual environment $VENV_DIR activated."
    echo "Python is: `which python3.9`"
    echo "Pip is: `which pip3.9`"
    python3.9 -V 
    pip3.9 -V
}

if [ -d "$VENV_DIR" ]; then
    venv_activate
else
    echo "Virtual environment $VENV_DIR does not exist. Creating..."
    venv_create && venv_activate
fi