#!/bin/bash
# filename: venv_py
# description: create and|or activate virtual environment for python3
# Usage: . venv_py
# 脚本等同于执行命令：python3 -m venv .venv_py && source .venv_py/bin/activate
# 若要创建虚拟环境前清理目标目录: python3 -m venv .venv_py --clear

# 设置 Python 解释器路径和虚拟环境目录
PYTHON_BIN=/usr/bin/python3.10
VENV=.venv_py
VENV_DIR=$(pwd)/$VENV

venv_create() {
    echo "Using $PYTHON_BIN"
    echo "Creating virtual environment at: $VENV_DIR"
    $PYTHON_BIN -m venv $VENV
    echo
}

venv_activate() {
    echo "Activate with: source $VENV/bin/activate"
    source $VENV/bin/activate
    echo "Virtual environment $VENV activated."
    echo "which python:     `which python`"
    echo "which pip:        `which pip`"
    python -V
    pip -V
}

if [ -d "$VENV_DIR" ]; then
    venv_activate
else
    venv_create && venv_activate
fi
