#!/bin/bash
# filename: venv_py
# description: create and|or activate virtual environment for python3
# Usage: . venv_py
# 脚本等同于执行命令：python3 -m venv venv_py && source venv_py/bin/activate
# 若要创建虚拟环境前清理目标目录: python3 -m venv venv_py --clear

# 设置 Python 解释器路径和虚拟环境目录
PYTHON_BIN=/usr/bin/python3
VENV_DIR=venv_py

venv_create() {
    $PYTHON_BIN -m venv $VENV_DIR
}

venv_activate() {
    source $VENV_DIR/bin/activate
    echo "Virtual environment $VENV_DIR activated."
    echo "Python is: `which python3`"
    echo "Pip is: `which pip3`"
    python3 -V 
    pip3 -V
}

if [ -d "$VENV_DIR" ]; then
    venv_activate
else
    echo "Virtual environment $VENV_DIR does not exist. Creating..."
    venv_create && venv_activate
fi
